version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: azerBook
    environment:
      POSTGRES_USER: vusal
      POSTGRES_PASSWORD: azerbook55
      POSTGRES_DB: book
    ports:
      - "5432:5432"
    volumes:
      - azerbook_db_volume:/var/lib/postgresql/data
      - ./setup_booking.sql:/docker-entrypoint-initdb.d/setup_booking.sql
    restart: unless-stopped
    networks:
      - azerbook-net


#Backend Service
  backend:
    build: .
    container_name: azerbook_backend
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/book
      DB_USER: vusal
      DB_PASS: azerbook55
      JWT_ACCESS_SECRET: SAXTAVnVzYWxBemVyYm9va0xvY2FsU2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb24=
      JWT_REFRESH_SECRET: VnVzYWxBemVyYm9va0xvY2FsU2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb24=
    ports:
      - "8080:8080"
    networks:
      - azerbook-net

#Frontend Service
  frontend:
    build: ./frontend
    container_name: azerbook_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - azerbook-net


volumes:
  azerbook_db_volume:


networks:
  azerbook-net:
    driver: bridge


