

spring:
  application:
    name: Azerbook
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/book}
    username: ${DB_USER:vusal}
    password: ${DB_PASS:azerbook55}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}



jwt:
  access-secret: ${JWT_ACCESS_SECRET:SAXTAVnVzYWxBemVyYm9va0xvY2FsU2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb24=}
  refresh-secret: ${JWT_REFRESH_SECRET:SAXTAVnVzYWxBemVyYm9va0xvY2FsU2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb24=}
  access-expiration: 900000
  refresh-expiration: 604800000

