

spring:
  application:
    name: Azerbook
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/book}
    username: ${DB_USER:vusal}
    password: ${DB_PASS:azerbook55}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080



jwt:
  access-secret: HJp3ANdvf8aG/r6dN6Tb/zh/bldF78bsylojKPYptlU=
  refresh-secret: 6/CwOpck/s7epm39OwrXJHEPufqMQM4kDrrAXfjPdik=
  access-expiration: 900000
  refresh-expiration: 604800000

