

spring:
  application:
    name: Azerbook
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: vusal
    password: azerbook55
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080


cloudinary:
  cloud-name: dxmoidh8h
  api-key: 534827334111367
  api-secret: miDaXznGvXNOIUowsmjhZKg54sA
