import { Hotel, Destination, Booking } from './types';

export const destinations: Destination[] = [
  {
    id: '1',
    name: 'Bakı',
    slug: 'baku',
    hotelCount: 142,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Azərbaycanın paytaxtı, qədim şəhər qapıları ilə müasir memarluğun qovuşduğu yer',
    tagline: 'Modern & Qədim',
  },
  {
    id: '2',
    name: 'Şəki',
    slug: 'sheki',
    hotelCount: 38,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Tarixi ipək yolu şəhəri, Xan Sarayı ilə məşhur',
    tagline: 'Tarixi & Mədəni',
  },
  {
    id: '3',
    name: 'Qəbələ',
    slug: 'gabala',
    hotelCount: 56,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    description: 'Azərbaycanın turizm paytaxtı, dağlar arasında yerləşən mavi göl',
    tagline: 'Təbiət & Macəra',
  },
  {
    id: '4',
    name: 'Quba',
    slug: 'quba',
    hotelCount: 24,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    description: 'Qafqaz dağlarının ətəyindəki gözəl şəhər, alma bağları ilə məşhur',
    tagline: 'Dağlar & Mənzərə',
  },
  {
    id: '5',
    name: 'Şahdağ',
    slug: 'shahdag',
    hotelCount: 18,
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    description: 'Azərbaycanın dağ-xizək kurort zonası, dörd mövsümlük istirahət',
    tagline: 'Xizək & Dağ',
  },
  {
    id: '6',
    name: 'Naftalan',
    slug: 'naftalan',
    hotelCount: 12,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
    description: 'Dünyada yeganə neft müalicəsi kurort şəhəri',
    tagline: 'Sağlıq & Wellness',
  },
];

export const hotels: Hotel[] = [
  {
    id: '1',
    name: 'Four Seasons Hotel Baku',
    slug: 'four-seasons-baku',
    city: 'Bakı',
    citySlug: 'baku',
    address: '1 Neftçilər pr., Bakı',
    stars: 5,
    rating: 9.6,
    reviewCount: 523,
    ratingLabel: 'Əla',
    pricePerNight: 780,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
    ],
    amenities: ['WiFi', 'Pool', 'Spa', 'Breakfast', 'Parking', 'Gym', 'Sea view', 'Restaurant', 'Bar', 'Room service'],
    description: 'Four Seasons Hotel Baku Xəzər dənizinin sahilindəki ən lüks oteldır. Üç üzgüçülük hovuzu, dünya səviyyəli Spa mərkəzi və bir neçə restoran ilə qonaqlarımıza unutulmaz bir istirahət təklif edirik. Bakının tarixi mərkəzinə piyada məsafəsindədir.',
    type: 'Hotel',
    badge: 'Seçilmiş',
    urgency: 'Son 2 otaq!',
    lat: 40.3777,
    lng: 49.8533,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Sahil',
    rooms: [
      {
        id: 'r1',
        name: 'Deluxe Otaq',
        bedType: 'King size çarpayı',
        capacity: 2,
        size: 45,
        price: 780,
        amenities: ['WiFi', 'Minibar', 'Şəhər mənzərəsi', 'Küvet'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 2,
      },
      {
        id: 'r2',
        name: 'Premier Suite',
        bedType: '2 King size çarpayı',
        capacity: 4,
        size: 85,
        price: 1250,
        amenities: ['WiFi', 'Minibar', 'Dəniz mənzərəsi', 'Jacuzzi', 'Salon'],
        image: 'https://images.unsplash.com/photo-1591088398332-8596b4a7c5de?w=800&q=80',
        cancellation: 'Pulsuz ləğv (48 saat əvvəl)',
        available: 1,
      },
    ],
    reviews: [
      {
        id: 'rv1',
        userName: 'Əli Həsənov',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ali',
        country: 'Azərbaycan',
        date: '2024-11-15',
        rating: 9.8,
        comment: 'Möhtəşəm xidmət, qeyri-adi mənzərə. Hər şey mükəmməl idi. Mütləq tövsiyə edirəm!',
        helpful: 24,
        categories: { cleanliness: 10, location: 10, service: 9.8, value: 9.0 },
      },
      {
        id: 'rv2',
        userName: 'Sarah Johnson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        country: 'ABŞ',
        date: '2024-10-20',
        rating: 9.4,
        comment: 'Absolutely stunning hotel. The views of the Caspian Sea are breathtaking. Staff was incredibly helpful and professional.',
        helpful: 18,
        categories: { cleanliness: 9.5, location: 9.8, service: 9.5, value: 8.8 },
      },
    ],
  },
  {
    id: '2',
    name: 'JW Marriott Absheron',
    slug: 'jw-marriott-absheron',
    city: 'Bakı',
    citySlug: 'baku',
    address: 'Azadlıq Meydanı 2, Bakı',
    stars: 5,
    rating: 9.2,
    reviewCount: 387,
    ratingLabel: 'Əla',
    pricePerNight: 620,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200&q=80',
      'https://images.unsplash.com/photo-1584132869994-873f9363a562?w=800&q=80',
      'https://images.unsplash.com/photo-1560347876-aeef00ee58a1?w=800&q=80',
      'https://images.unsplash.com/photo-1587985064135-0366536eab42?w=800&q=80',
    ],
    amenities: ['WiFi', 'Pool', 'Spa', 'Breakfast', 'Gym', 'Bar', 'Restaurant', 'Room service'],
    description: 'JW Marriott Absheron Bakı şəhərinin ürəyindədir. Azadlıq Meydanına baxan bu möhtəşəm otel, Xəzər dənizinin panoramik mənzərəsini təklif edir. Beş ulduzlu xidmət standartları ilə qonaqlarımızı həmişə məmnun edirik.',
    type: 'Hotel',
    urgency: 'Son 3 otaq!',
    lat: 40.3693,
    lng: 49.8358,
    checkInTime: '15:00',
    checkOutTime: '12:00',
    neighborhood: 'Mərkəz',
    rooms: [
      {
        id: 'r3',
        name: 'Superior Otaq',
        bedType: 'Twin çarpayılar',
        capacity: 2,
        size: 38,
        price: 620,
        amenities: ['WiFi', 'Minibar', 'Şəhər mənzərəsi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 3,
      },
    ],
    reviews: [
      {
        id: 'rv3',
        userName: 'Nigar Məmmədova',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nigar',
        country: 'Azərbaycan',
        date: '2024-11-08',
        rating: 9.2,
        comment: 'Çox gözəl otel, hər şey yerli-yerindəydi. Xidmət keyfiyyəti yüksəkdir.',
        helpful: 12,
        categories: { cleanliness: 9.5, location: 9.8, service: 9.0, value: 8.8 },
      },
    ],
  },
  {
    id: '3',
    name: 'Sheki Palace Hotel',
    slug: 'sheki-palace',
    city: 'Şəki',
    citySlug: 'sheki',
    address: 'Şəkinin tarixi mərkəzi',
    stars: 4,
    rating: 9.0,
    reviewCount: 234,
    ratingLabel: 'Çox yaxşı',
    pricePerNight: 180,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80',
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
      'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    amenities: ['WiFi', 'Breakfast', 'Parking', 'Restaurant', 'Garden', 'Room service'],
    description: 'Tarixi Şəki şəhərinin mərkəzindəki bu unikal otel, Xan Sarayına piyada məsafəsindədir. Otaqlar ənənəvi Azərbaycan memarlığı ilə müasir rahatlıqları birləşdirir.',
    type: 'Hotel',
    badge: 'Tövsiyə edilir',
    lat: 41.1897,
    lng: 47.1700,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Köhnə Şəhər',
    rooms: [
      {
        id: 'r5',
        name: 'Standart Otaq',
        bedType: 'Double çarpayı',
        capacity: 2,
        size: 28,
        price: 180,
        amenities: ['WiFi', 'Bahçə mənzərəsi', 'Kondisioner'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 5,
      },
    ],
    reviews: [
      {
        id: 'rv5',
        userName: 'Mikael Schmidt',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mikael',
        country: 'Almaniya',
        date: '2024-09-15',
        rating: 9.1,
        comment: 'Wunderschönes Hotel im historischen Zentrum. Das Frühstück war hervorragend!',
        helpful: 8,
        categories: { cleanliness: 9.0, location: 9.5, service: 9.2, value: 9.3 },
      },
    ],
  },
  {
    id: '4',
    name: 'Gabala Riverside Resort',
    slug: 'gabala-riverside',
    city: 'Qəbələ',
    citySlug: 'gabala',
    address: 'Qəbələ Turizm Zonas, Qəbələ',
    stars: 5,
    rating: 9.4,
    reviewCount: 456,
    ratingLabel: 'Əla',
    pricePerNight: 340,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
      'https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=800&q=80',
      'https://images.unsplash.com/photo-1523544545801-c08e1e39cd73?w=800&q=80',
    ],
    amenities: ['WiFi', 'Pool', 'Spa', 'Breakfast', 'Parking', 'Gym', 'Restaurant', 'Tennis', 'Kids Club'],
    description: 'Qəbələnin möhtəşəm dağ mənzərəsi fonunda yerləşən bu lüks resort, Azərbaycanın ən gözəl istirahət komplekslərindən biridir. Sonsuz pool, dünya səviyyəli spa mərkəzi və müxtəlif idman sahələri ilə ailə istirahəti üçün mükəmmel seçimdir.',
    type: 'Resort',
    badge: 'Ən Yaxşı Seçim',
    urgency: 'Son 3 otaq!',
    lat: 40.9981,
    lng: 47.8453,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    neighborhood: 'Turizm Zonas',
    rooms: [
      {
        id: 'r7',
        name: 'Dağ Mənzərəli Otaq',
        bedType: 'King size çarpayı',
        capacity: 2,
        size: 40,
        price: 340,
        amenities: ['WiFi', 'Dağ mənzərəsi', 'Balkon', 'Minibar'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (48 saat əvvəl)',
        available: 3,
      },
    ],
    reviews: [
      {
        id: 'rv7',
        userName: 'Leyla Əliyeva',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leyla',
        country: 'Azərbaycan',
        date: '2024-08-20',
        rating: 9.5,
        comment: 'Fantastik resort! Uşaqlar üçün çox əyləncəlidir. Mütləq bir daha gələcəyik.',
        helpful: 31,
        categories: { cleanliness: 9.5, location: 9.8, service: 9.3, value: 9.0 },
      },
    ],
  },
  {
    id: '5',
    name: 'Shahdag Mountain Resort',
    slug: 'shahdag-mountain',
    city: 'Şahdağ',
    citySlug: 'shahdag',
    address: 'Şahdağ Turizm Kompleksi, Quba',
    stars: 5,
    rating: 9.3,
    reviewCount: 312,
    ratingLabel: 'Əla',
    pricePerNight: 450,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1517825738774-7de9363ef735?w=1200&q=80',
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80',
    ],
    amenities: ['WiFi', 'Spa', 'Breakfast', 'Ski access', 'Gym', 'Restaurant', 'Bar', 'Fireplace'],
    description: 'Şahdağ dağ kurortunda yerləşən bu lüks resort, xizək mövsümündə və yay dövründə qonaqlara unutulmaz bir istirahət təklif edir. Ski in/ski out imkanı, istilik hovuzları və dağ mənzərəsi ilə qonaqlarınızı rifahlandırın.',
    type: 'Resort',
    lat: 41.2965,
    lng: 48.5832,
    checkInTime: '15:00',
    checkOutTime: '12:00',
    neighborhood: 'Dağ Kurort Zonas',
    rooms: [
      {
        id: 'r9',
        name: 'Ski Chalet Suite',
        bedType: 'King size çarpayı',
        capacity: 2,
        size: 55,
        price: 450,
        amenities: ['WiFi', 'Dağ mənzərəsi', 'Şömine', 'Jacuzzi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (72 saat əvvəl)',
        available: 4,
      },
    ],
    reviews: [
      {
        id: 'rv9',
        userName: 'Rauf Nəsirov',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rauf',
        country: 'Azərbaycan',
        date: '2024-01-15',
        rating: 9.4,
        comment: 'Xizək taydımızın ən gözəl yeri. Hər şey mükəmməl təşkil edilmişdi.',
        helpful: 19,
        categories: { cleanliness: 9.5, location: 10, service: 9.2, value: 9.0 },
      },
    ],
  },
  {
    id: '6',
    name: 'Naftalan Sanatorium & Spa',
    slug: 'naftalan-sanatorium',
    city: 'Naftalan',
    citySlug: 'naftalan',
    address: 'Naftalan kurort şəhəri',
    stars: 4,
    rating: 8.8,
    reviewCount: 189,
    ratingLabel: 'Çox yaxşı',
    pricePerNight: 220,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    ],
    amenities: ['WiFi', 'Spa', 'Breakfast', 'Medical center', 'Pool', 'Gym', 'Restaurant'],
    description: 'Dünyada yeganə olan neft müalicəsi kurortunda yerləşən bu sanatoriyanın xüsusi neft vannaları sistemi, müxtəlif xəstəliklərə müalicəvi təsir göstərir. Tam all-inclusive paketimiz ilə rahatlıq içində sağlam qalın.',
    type: 'Resort',
    lat: 40.5054,
    lng: 46.8258,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Kurort Mərkəzi',
    rooms: [
      {
        id: 'r11',
        name: 'Müalicəvi Suite',
        bedType: 'Twin çarpayılar',
        capacity: 2,
        size: 35,
        price: 220,
        amenities: ['WiFi', 'Neft vanası', 'Tibbi xidmət', 'All-inclusive'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (48 saat əvvəl)',
        available: 6,
      },
    ],
    reviews: [
      {
        id: 'rv11',
        userName: 'Tamara İvanova',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tamara',
        country: 'Rusiya',
        date: '2024-07-10',
        rating: 8.9,
        comment: 'Прекрасное место для лечения. Процедуры с нефтью очень помогли при болях в суставах.',
        helpful: 15,
        categories: { cleanliness: 9.0, location: 8.5, service: 9.0, value: 9.2 },
      },
    ],
  },
  {
    id: '7',
    name: 'Quba Highland Resort',
    slug: 'quba-highland',
    city: 'Quba',
    citySlug: 'quba',
    address: 'Quba Dağ Turizm Zonas',
    stars: 4,
    rating: 8.9,
    reviewCount: 156,
    ratingLabel: 'Çox yaxşı',
    pricePerNight: 160,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=1200&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
      'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=800&q=80',
    ],
    amenities: ['WiFi', 'Breakfast', 'Parking', 'Restaurant', 'Hiking trails', 'BBQ area'],
    description: 'Quba dağlarının arasındakı bu rahat resort, şəhər həyatından uzaqlaşmaq istəyənlər üçün ideal seçimdir. Yaxınlığındakı Qudyalçay vadisi trekking marşrutları ilə məşhurdur.',
    type: 'Resort',
    lat: 41.3600,
    lng: 48.5300,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Dağ Bölgəsi',
    rooms: [
      {
        id: 'r13',
        name: 'Chalet Otaq',
        bedType: 'Double çarpayı',
        capacity: 2,
        size: 32,
        price: 160,
        amenities: ['WiFi', 'Dağ mənzərəsi', 'Balkon'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 7,
      },
    ],
    reviews: [],
  },
  {
    id: '8',
    name: 'Baku Inn Boutique Hotel',
    slug: 'baku-inn-boutique',
    city: 'Bakı',
    citySlug: 'baku',
    address: 'İçərişəhər, Bakı',
    stars: 4,
    rating: 9.1,
    reviewCount: 298,
    ratingLabel: 'Çox yaxşı',
    pricePerNight: 280,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
      'https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800&q=80',
    ],
    amenities: ['WiFi', 'Breakfast', 'Bar', 'Restaurant', 'Concierge', 'Laundry'],
    description: 'Bakının tarixi İçərişəhər qalasının yanında yerləşən bu butik otel, unikal Azərbaycan memarlıq elementlərini müasir dizaynla birləşdirir. Köhnə şəhərin daşlarıyla örtülü küçələrə baxan pəncərələr sizi əsrlər öncəyə aparır.',
    type: 'Hotel',
    badge: 'Boutique',
    lat: 40.3677,
    lng: 49.8357,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    neighborhood: 'İçərişəhər',
    rooms: [
      {
        id: 'r15',
        name: 'Heritage Otaq',
        bedType: 'Queen size çarpayı',
        capacity: 2,
        size: 30,
        price: 280,
        amenities: ['WiFi', 'Şəhər mənzərəsi', 'Minibar'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 4,
      },
    ],
    reviews: [],
  },
  {
    id: '9',
    name: 'Ganja Grand Hotel',
    slug: 'ganja-grand',
    city: 'Gəncə',
    citySlug: 'ganja',
    address: 'Gəncə Bulvarı, Gəncə',
    stars: 4,
    rating: 8.6,
    reviewCount: 124,
    ratingLabel: 'Yaxşı',
    pricePerNight: 140,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=1200&q=80',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    ],
    amenities: ['WiFi', 'Breakfast', 'Parking', 'Pool', 'Restaurant', 'Gym'],
    description: 'Azərbaycanın ikinci böyük şəhəri Gəncədə yerləşən bu müasir otel, şəhərin mərkəzinə yaxın mövqeyilə seçilir. Nizami Gəncəvinin vətəni olan bu tarixi şəhəri kəşf edərkən rahat bir baza kimi istifadə edin.',
    type: 'Hotel',
    lat: 40.6828,
    lng: 46.3606,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Şəhər Mərkəzi',
    rooms: [
      {
        id: 'r17',
        name: 'Standart Otaq',
        bedType: 'Double çarpayı',
        capacity: 2,
        size: 28,
        price: 140,
        amenities: ['WiFi', 'Şəhər mənzərəsi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 8,
      },
    ],
    reviews: [],
  },
  {
    id: '10',
    name: 'Caspian Waterfront Hotel',
    slug: 'caspian-waterfront',
    city: 'Bakı',
    citySlug: 'baku',
    address: 'Həsənbəy Zərdabi pr., Bakı',
    stars: 3,
    rating: 8.2,
    reviewCount: 215,
    ratingLabel: 'Yaxşı',
    pricePerNight: 130,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1521782462922-9318be56ca4f?w=1200&q=80',
      'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=800&q=80',
    ],
    amenities: ['WiFi', 'Sea view', 'Breakfast', 'Parking', 'Restaurant'],
    description: 'Xəzər dənizinin göründüyü bu rahat otel, Bakıya gələn səyahətçilər üçün sərfəli qiymətə keyfiyyətli xidmət təklif edir. Sahil bulvarına 5 dəqiqəlik piyada məsafəsindədir.',
    type: 'Hotel',
    lat: 40.3650,
    lng: 49.8250,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: 'Sahil',
    rooms: [
      {
        id: 'r19',
        name: 'Dəniz Mənzərəli Otaq',
        bedType: 'Double çarpayı',
        capacity: 2,
        size: 24,
        price: 130,
        amenities: ['WiFi', 'Dəniz mənzərəsi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 6,
      },
    ],
    reviews: [],
  },
  {
    id: '11',
    name: 'Gabala Comfort Inn',
    slug: 'gabala-comfort',
    city: 'Qəbələ',
    citySlug: 'gabala',
    address: 'Qəbələ şəhəri, Qəbələ',
    stars: 3,
    rating: 8.5,
    reviewCount: 167,
    ratingLabel: 'Yaxşı',
    pricePerNight: 95,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=1200&q=80',
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    ],
    amenities: ['WiFi', 'Breakfast', 'Parking', 'Garden', 'BBQ'],
    description: 'Qəbələnin yaşıl təbiəti arasında yerləşən bu rahat otel, ailə istirahəti üçün ideal seçimdir. Mehriban heyəti, ev yemkləri və geniş bağı ilə ev rahatlığını sizə yaşadır.',
    type: 'Guesthouse',
    lat: 40.9800,
    lng: 47.8500,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    neighborhood: 'Şəhər Mərkəzi',
    rooms: [
      {
        id: 'r21',
        name: 'Standart Ailə Otağı',
        bedType: 'Twin çarpayılar',
        capacity: 3,
        size: 30,
        price: 95,
        amenities: ['WiFi', 'Bağ mənzərəsi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 5,
      },
    ],
    reviews: [],
  },
  {
    id: '12',
    name: 'Baku City Express',
    slug: 'baku-city-express',
    city: 'Bakı',
    citySlug: 'baku',
    address: '28 May küç., Bakı',
    stars: 3,
    rating: 7.8,
    reviewCount: 342,
    ratingLabel: 'Yaxşı',
    pricePerNight: 85,
    currency: 'AZN',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80',
      'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=800&q=80',
    ],
    amenities: ['WiFi', 'Parking', 'Restaurant', '24/7 reception'],
    description: 'Bakı mərkəzindəki bu biznes oteli, səyahət edənlər üçün əlverişli qiymətə keyfiyyətli xidmət təklif edir. Metro stansiyasına yaxın mövqeyi ilə şəhəri asanlıqla kəşf edə bilərsiniz.',
    type: 'Hotel',
    lat: 40.3790,
    lng: 49.8480,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    neighborhood: '28 May',
    rooms: [
      {
        id: 'r23',
        name: 'Standart Otaq',
        bedType: 'Single çarpayı',
        capacity: 1,
        size: 20,
        price: 85,
        amenities: ['WiFi', 'Şəhər mənzərəsi'],
        image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        cancellation: 'Pulsuz ləğv (24 saat əvvəl)',
        available: 10,
      },
    ],
    reviews: [],
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    reference: 'AZB-2024-78432',
    hotelId: '1',
    hotelName: 'Four Seasons Hotel Baku',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
    roomName: 'Deluxe Otaq',
    checkIn: '2025-03-15',
    checkOut: '2025-03-18',
    adults: 2,
    children: 0,
    totalPrice: 2340,
    status: 'confirmed',
    guestName: 'Əli Həsənov',
    guestEmail: 'ali@example.com',
    createdAt: '2025-02-10',
  },
  {
    id: 'b2',
    reference: 'AZB-2024-65210',
    hotelId: '4',
    hotelName: 'Gabala Riverside Resort',
    hotelImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
    roomName: 'Dağ Mənzərəli Otaq',
    checkIn: '2025-04-01',
    checkOut: '2025-04-05',
    adults: 2,
    children: 1,
    totalPrice: 1360,
    status: 'confirmed',
    guestName: 'Əli Həsənov',
    guestEmail: 'ali@example.com',
    createdAt: '2025-02-15',
  },
  {
    id: 'b3',
    reference: 'AZB-2023-44521',
    hotelId: '3',
    hotelName: 'Sheki Palace Hotel',
    hotelImage: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&q=80',
    roomName: 'Standart Otaq',
    checkIn: '2024-09-10',
    checkOut: '2024-09-13',
    adults: 2,
    children: 0,
    totalPrice: 540,
    status: 'completed',
    guestName: 'Əli Həsənov',
    guestEmail: 'ali@example.com',
    createdAt: '2024-08-20',
  },
];

export const getRatingLabel = (rating: number): string => {
  if (rating >= 9.5) return 'Əla';
  if (rating >= 9.0) return 'Əla';
  if (rating >= 8.5) return 'Çox yaxşı';
  if (rating >= 8.0) return 'Yaxşı';
  if (rating >= 7.0) return 'Yaxşı';
  return 'Kafi';
};

export const getRatingColor = (rating: number): string => {
  if (rating >= 9.0) return 'bg-emerald-600';
  if (rating >= 8.0) return 'bg-green-500';
  if (rating >= 7.0) return 'bg-amber-500';
  return 'bg-orange-500';
};

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('az-AZ').format(price);
};
